version: '3.8'

services:
  database:
    container_name: url_checker_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_checker
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: url_checker_php
    build:
      context: ./tools/docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/url-checker
    depends_on:
      - database
  nginx:
    container_name: url_checker_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/url-checker
      - ./tools/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database